version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11-browsers
      
    working_directory: ~/react-circosJS

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      - run: yarn lint
      - run: yarn test:units
      - run: yarn test:screenshots

